// Generated by CoffeeScript 1.4.0
(function() {
  var LogEntry, LogEntryList, LogEntryView,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  LogEntry = (function(_super) {

    __extends(LogEntry, _super);

    function LogEntry() {
      return LogEntry.__super__.constructor.apply(this, arguments);
    }

    return LogEntry;

  })(Backbone.Model);

  LogEntryList = (function(_super) {

    __extends(LogEntryList, _super);

    function LogEntryList() {
      return LogEntryList.__super__.constructor.apply(this, arguments);
    }

    LogEntryList.prototype.model = LogEntry;

    LogEntryList.prototype.localStorage = new Backbone.LocalStorage("exercise-log-db");

    return LogEntryList;

  })(Backbone.Collection);

  LogEntryView = (function(_super) {

    __extends(LogEntryView, _super);

    function LogEntryView() {
      return LogEntryView.__super__.constructor.apply(this, arguments);
    }

    LogEntryView.prototype.tagName = "tr";

    LogEntryView.prototype.template = _.template($('#row-item').html());

    return LogEntryView;

  })(Backbone.View);

}).call(this);
